### PR TITLE
Reading in building permits data from 2019 and 2020

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo issuedate and lastmodified don't appear to be reading in, though I'm not sure of how big of an issue that is?

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 nice catch. The rest of the variables look OK though?

**Comment by ahariharan7** [comment]
Yep!
________________________________

**Comment by rpitingolo** [comment]
@ahariharan7 thanks. Looks like they changed the date format from yyyy-mm-dd to yyyymmdd. I updated the macro to account for that. Can you rerun your programs and re-check the output? Thanks!

**Comment by ahariharan7** [comment]
@rpitingolo whenever you're ready!

**Comment by rpitingolo** [comment]
@ahariharan7 looks good, please go ahead and merge, sync and batch submit these! After you batch submit please double check the logs for errors. I got a weird error on the proc mapimport when I tested, but I re-started the SAS session and didn't get it again. So not sure what happened with that but we should make sure the batch submit is successful.

**Pull request merged**
